### ISSUE TITLE
Keep the VSCode extension update to date

### ISSUE THREAD

**Issue by seven332** [dawn-gpu/tintd-bundler#1]
Would you mind update the VSCode extension? https://marketplace.visualstudio.com/items?itemName=gfx-tintd.tintd

I want to use the feature dual-source blending, but it still ask me to enable chromium_internal_dual_source_blending.

**Comment by greggman** [comment]
you can try the new version. I have not tried yet 😅

**Comment by seven332** [comment]
It works. Thank you.
